services:

  app:
    build: .
    ports:
    - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]    
      interval: 1m30s
      timeout: 3s
      retries: 5
      start_period: 30s

volumes:
  pgdata:

  